---
title: "R Notebook"
output: html_notebook
---

```{r}
library(biomod2)
library(raster)
library(sf)
library(tidyverse)
library(doParallel)
```

VICUGNA
```{r}
#VICUGNA

library(dplyr)
#setear el working directory en la carpeta donde estén las carpetas "mensalis", "vicugna" e "hybrid".
setwd("S:/UACh/vicuñas/chelsa_historico/bio")

#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311.models.out')
vicugna_en=load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311ensemble.models.out')
model_en <- get(vicugna_en)

#con @ se exploran los diferentes ouputs

#nombres de las variables seleccionadas en el modelo final
vicugna.1659920311.models.out@expl.var.names

#evaluación de los modelos por separado:
w=as_tibble(vicugna.1659920311.models.out@models.evaluation@val,rownames='names')

test_eval_maxent=w %>% select(starts_with('Testing.data.MAXENT.Phillips.Full')) %>% add_column(stat=rownames(vicugna.1659920311.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_gbm=w %>% select(starts_with('Testing.data.GBM.Full')) %>% add_column(stat=rownames(vicugna.1659920311.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_rf=w %>% select(starts_with('Testing.data.RF.Full')) %>% add_column(stat=rownames(vicugna.1659920311.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

#evaluación de los ensambles de modelos 

w=as_tibble(get_evaluations(model_en),rownames='names') %>% select(starts_with('vicugna_EMmeanByACCURACY_mergedAlgo_Full'))
test_eval_ensemble=data.frame(PA1=c(KAPPA=0,TSS=0,ROC=0))

for (i in 1:5){
  a=w[[i]][,1]
  test_eval_ensemble[paste('PA',i,sep='')]=a
}

test_eval_ensemble['mean']=rowMeans(test_eval_ensemble)

#importancia de variables en modelos por separado

w=as_tibble(vicugna.1659920311.models.out@variables.importances@val,rownames='names')

var_imp_maxent=w %>% select(starts_with('MAXENT.Phillips.Full')) %>% add_column(var=rownames(vicugna.1659920311.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("MAXENT")))) 

var_imp_gbm=w %>% select(starts_with('GBM.Full')) %>% add_column(var=rownames(vicugna.1659920311.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("GBM")))) 

var_imp_rf=w %>% select(starts_with('RF.Full')) %>% add_column(var=rownames(vicugna.1659920311.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("RF")))) 

#importancia de variables en ensambles

w=as_tibble(get_variables_importance(model_en),rownames='names') %>% select(contains(c('vicugna_EMcvByACCURACY_mergedAlgo_Full','names')))
varimp_ensemble=data.frame(PA1=rep(0,length(w$names)));rownames(varimp_ensemble)=w$names

for (i in 1:5){
  o=seq(5*(i-1)+1,i*5)
  a=mutate(w[o], mean = rowMeans(across(starts_with("rand"))))[6]
  varimp_ensemble[paste('PA',i,sep='')]=a
}

varimp_ensemble['mean']=rowMeans(varimp_ensemble)

```

Curvas de respuesta:

Por modelo
```{r}
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311.models.out')

vicugna_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311.models.out')
my_model <- get(vicugna_mod)

model=BIOMOD_LoadModels(my_model, models = c('GBM','RF','MAXENT.Phillips'))
model=model[seq(21,315,21)]#se muestrans los modelos "full"

myRespPlot2D <- 
  response.plot2(models = model, Data = get_formal_data(my_model, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean',
    col = c(rep("blue",5), rep("red",5),rep("green",5)),legend = TRUE)
```

Por ensamble
```{r}
#se carga el modelo a evaluar
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311ensemble.models.out')

#se carga el archivo con los ensambles
vicugna_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311ensemble.models.out')
my_model <- get(vicugna_mod)
#se carga el archivo con los modelos por separado (solo se usa para obtener los valores de las variables)
vicugna_mod2=load('S:/UACh/vicuñas/chelsa_historico/bio/vicugna/vicugna.1659920311.models.out')
my_model2 <- get(vicugna_mod2)

#se seleccionan los ensambles "full" (combinación de corridas), promediados por Accuracy
model=c("vicugna_EMmeanByACCURACY_mergedAlgo_Full_PA1","vicugna_EMmeanByACCURACY_mergedAlgo_Full_PA2","vicugna_EMmeanByACCURACY_mergedAlgo_Full_PA3","vicugna_EMmeanByACCURACY_mergedAlgo_Full_PA4","vicugna_EMmeanByACCURACY_mergedAlgo_Full_PA5")
#para ver todos los ensambles disponibles: 
BIOMOD_LoadModels(my_model, models = c('PA1','PA2','PA3','PA4','PA5'))

#se grafican las curvas de respuesta
myRespPlot2D <- response.plot2(models = model, Data = get_formal_data(my_model2, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean', col = c('#d9ed92', "#99d98c","#52b69a","#1a759f","#184e77",),legend = TRUE)
```
MENSALIS
```{r}
#VICUGNA

#vicugna.1647805880.models.out   vicugna.1647805880ensemble.models.out
#mensalis.1647885696.models.out  mensalis.1647885696ensemble.models.out
#hybrid.1659671505.models.out    hybrid.1659671505ensemble.models.out


library(dplyr)
#setear el working directory en la carpeta donde estén las carpetas "vicugna", "mensalis" e "hybrid".
setwd("S:/UACh/vicuñas/chelsa_historico/bio")

#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505.models.out')
mensalis_en=load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505ensemble.models.out')
model_en <- get(mensalis_en)

#con @ se exploran los diferentes ouputs

#nombres de las variables seleccionadas en el modelo final
mensalis.1659671505.models.out@expl.var.names

#evaluación de los modelos por separado:
w=as_tibble(mensalis.1659671505.models.out@models.evaluation@val,rownames='names')

test_eval_maxent=w %>% select(starts_with('Testing.data.MAXENT.Phillips.Full')) %>% add_column(stat=rownames(mensalis.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_gbm=w %>% select(starts_with('Testing.data.GBM.Full')) %>% add_column(stat=rownames(mensalis.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_rf=w %>% select(starts_with('Testing.data.RF.Full')) %>% add_column(stat=rownames(mensalis.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

#evaluación de los ensambles de modelos 

w=as_tibble(get_evaluations(model_en),rownames='names') %>% select(starts_with('mensalis_EMmeanByACCURACY_mergedAlgo_Full'))
test_eval_ensemble=data.frame(PA1=c(KAPPA=0,TSS=0,ROC=0))

for (i in 1:5){
  a=w[[i]][,1]
  test_eval_ensemble[paste('PA',i,sep='')]=a
}

test_eval_ensemble['mean']=rowMeans(test_eval_ensemble)

#importancia de variables en modelos por separado

w=as_tibble(mensalis.1659671505.models.out@variables.importances@val,rownames='names')

var_imp_maxent=w %>% select(starts_with('MAXENT.Phillips.Full')) %>% add_column(var=rownames(mensalis.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("MAXENT")))) 

var_imp_gbm=w %>% select(starts_with('GBM.Full')) %>% add_column(var=rownames(mensalis.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("GBM")))) 

var_imp_rf=w %>% select(starts_with('RF.Full')) %>% add_column(var=rownames(mensalis.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("RF")))) 

#importancia de variables en ensambles

w=as_tibble(get_variables_importance(model_en),rownames='names') %>% select(contains(c('mensalis_EMcvByACCURACY_mergedAlgo_Full','names')))
varimp_ensemble=data.frame(PA1=rep(0,length(w$names)));rownames(varimp_ensemble)=w$names

for (i in 1:5){
  o=seq(5*(i-1)+1,i*5)
  a=mutate(w[o], mean = rowMeans(across(starts_with("rand"))))[6]
  varimp_ensemble[paste('PA',i,sep='')]=a
}

varimp_ensemble['mean']=rowMeans(varimp_ensemble)

```

Curvas de respuesta:

Por modelo
```{r}
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505.models.out')

mensalis_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505.models.out')
my_model <- get(mensalis_mod)

model=BIOMOD_LoadModels(my_model, models = c('GBM','RF','MAXENT.Phillips'))
model=model[seq(21,315,21)]#se muestrans los modelos "full"

myRespPlot2D <- 
  response.plot2(models = model, Data = get_formal_data(my_model, 'expl.var'), show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean',
    col = c(rep("blue",5), rep("red",5),rep("green",5)),legend = TRUE)
```

Por ensamble
```{r}
#se carga el modelo a evaluar
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505ensemble.models.out')

#se carga el archivo con los ensambles
mensalis_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505ensemble.models.out')
my_model <- get(mensalis_mod)
#se carga el archivo con los modelos por separado (solo se usa para obtener los valores de las variables)
mensalis_mod2=load('S:/UACh/vicuñas/chelsa_historico/bio/mensalis/mensalis.1659671505.models.out')
my_model2 <- get(mensalis_mod2)

#se seleccionan los ensambles "full" (combinación de corridas), promediados por Accuracy
model=c("mensalis_EMmeanByACCURACY_mergedAlgo_Full_PA1","mensalis_EMmeanByACCURACY_mergedAlgo_Full_PA2","mensalis_EMmeanByACCURACY_mergedAlgo_Full_PA3","mensalis_EMmeanByACCURACY_mergedAlgo_Full_PA4","mensalis_EMmeanByACCURACY_mergedAlgo_Full_PA5")
#para ver todos los ensambles disponibles: 
BIOMOD_LoadModels(my_model, models = c('PA1','PA2','PA3','PA4','PA5'))

#se grafican las curvas de respuesta
myRespPlot2D <- response.plot2(models = model, Data = get_formal_data(my_model2, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean', col = c('#d9ed92', "#99d98c","#52b69a","#1a759f","#184e77"),legend = TRUE)
```


HYBRID
```{r}

#vicugna.1647805880.models.out   vicugna.1647805880ensemble.models.out
#mensalis.1647885696.models.out  mensalis.1647885696ensemble.models.out
#hybrid.1659671505.models.out    hybrid.1659671505ensemble.models.out


library(dplyr)
#setear el working directory en la carpeta donde estén las carpetas "vicugna", "mensalis" e "hybrid".
setwd("S:/UACh/vicuñas/chelsa_historico/bio")

#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505.models.out')
hybrid_en=load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505ensemble.models.out')
model_en <- get(hybrid_en)

#con @ se exploran los diferentes ouputs

#nombres de las variables seleccionadas en el modelo final
hybrid.1659671505.models.out@expl.var.names

#evaluación de los modelos por separado:
w=as_tibble(hybrid.1659671505.models.out@models.evaluation@val,rownames='names')

test_eval_maxent=w %>% select(starts_with('Testing.data.MAXENT.Phillips.Full')) %>% add_column(stat=rownames(hybrid.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_gbm=w %>% select(starts_with('Testing.data.GBM.Full')) %>% add_column(stat=rownames(hybrid.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_rf=w %>% select(starts_with('Testing.data.RF.Full')) %>% add_column(stat=rownames(hybrid.1659671505.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

#evaluación de los ensambles de modelos 

w=as_tibble(get_evaluations(model_en),rownames='names') %>% select(starts_with('hybrid_EMmeanByACCURACY_mergedAlgo_Full'))
test_eval_ensemble=data.frame(PA1=c(KAPPA=0,TSS=0,ROC=0))

for (i in 1:5){
  a=w[[i]][,1]
  test_eval_ensemble[paste('PA',i,sep='')]=a
}

test_eval_ensemble['mean']=rowMeans(test_eval_ensemble)

#importancia de variables en modelos por separado

w=as_tibble(hybrid.1659671505.models.out@variables.importances@val,rownames='names')

var_imp_maxent=w %>% select(starts_with('MAXENT.Phillips.Full')) %>% add_column(var=rownames(hybrid.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("MAXENT")))) 

var_imp_gbm=w %>% select(starts_with('GBM.Full')) %>% add_column(var=rownames(hybrid.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("GBM")))) 

var_imp_rf=w %>% select(starts_with('RF.Full')) %>% add_column(var=rownames(hybrid.1659671505.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("RF")))) 

#importancia de variables en ensambles

w=as_tibble(get_variables_importance(model_en),rownames='names') %>% select(contains(c('hybrid_EMcvByACCURACY_mergedAlgo_Full','names')))
varimp_ensemble=data.frame(PA1=rep(0,length(w$names)));rownames(varimp_ensemble)=w$names

for (i in 1:5){
  o=seq(5*(i-1)+1,i*5)
  a=mutate(w[o], mean = rowMeans(across(starts_with("rand"))))[6]
  varimp_ensemble[paste('PA',i,sep='')]=a
}

varimp_ensemble['mean']=rowMeans(varimp_ensemble)

```

Curvas de respuesta:

Por modelo
```{r}
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505.models.out')

hybrid_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505.models.out')
my_model <- get(hybrid_mod)

model=BIOMOD_LoadModels(my_model, models = c('GBM','RF','MAXENT.Phillips'))
model=model[seq(21,315,21)]#se muestrans los modelos "full"

myRespPlot2D <- 
  response.plot2(models = model, Data = get_formal_data(my_model, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean',
    col = c(rep("blue",5), rep("red",5),rep("green",5)),legend = TRUE)
```

Por ensamble
```{r}
#se carga el modelo a evaluar
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505ensemble.models.out')

#se carga el archivo con los ensambles
hybrid_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505ensemble.models.out')
my_model <- get(hybrid_mod)
#se carga el archivo con los modelos por separado (solo se usa para obtener los valores de las variables)
hybrid_mod2=load('S:/UACh/vicuñas/chelsa_historico/bio/hybrid/hybrid.1659671505.models.out')
my_model2 <- get(hybrid_mod2)

#se seleccionan los ensambles "full" (combinación de corridas), promediados por Accuracy
model=c("hybrid_EMmeanByACCURACY_mergedAlgo_Full_PA1","hybrid_EMmeanByACCURACY_mergedAlgo_Full_PA2","hybrid_EMmeanByACCURACY_mergedAlgo_Full_PA3","hybrid_EMmeanByACCURACY_mergedAlgo_Full_PA4","hybrid_EMmeanByACCURACY_mergedAlgo_Full_PA5")
#para ver todos los ensambles disponibles: 
BIOMOD_LoadModels(my_model, models = c('PA1','PA2','PA3','PA4','PA5'))

#se grafican las curvas de respuesta
myRespPlot2D <- response.plot2(models = model, Data = get_formal_data(my_model2, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean', col = c('#d9ed92', "#99d98c","#52b69a","#1a759f","#184e77"),legend = TRUE)
```

ALL
```{r}

#vicugna.1647805880.models.out   vicugna.1647805880ensemble.models.out
#mensalis.1647885696.models.out  mensalis.1647885696ensemble.models.out
#hybrid.1659671505.models.out    hybrid.1659671505ensemble.models.out


library(dplyr)
#setear el working directory en la carpeta donde estén las carpetas "vicugna", "mensalis" e "all".
setwd("S:/UACh/vicuñas/chelsa_historico/bio")

#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313.models.out')
all_en=load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313ensemble.models.out')
model_en <- get(all_en)

#con @ se exploran los diferentes ouputs

#nombres de las variables seleccionadas en el modelo final
all.1659920313.models.out@expl.var.names

#evaluación de los modelos por separado:
w=as_tibble(all.1659920313.models.out@models.evaluation@val,rownames='names')

test_eval_maxent=w %>% select(starts_with('Testing.data.MAXENT.Phillips.Full')) %>% add_column(stat=rownames(all.1659920313.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_gbm=w %>% select(starts_with('Testing.data.GBM.Full')) %>% add_column(stat=rownames(all.1659920313.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

test_eval_rf=w %>% select(starts_with('Testing.data.RF.Full')) %>% add_column(stat=rownames(all.1659920313.models.out@models.evaluation@val)) %>% mutate(mean = rowMeans(across(starts_with("Testing")))) %>% select(tail(names(.), 2))

#evaluación de los ensambles de modelos 

w=as_tibble(get_evaluations(model_en),rownames='names') %>% select(starts_with('all_EMmeanByACCURACY_mergedAlgo_Full'))
test_eval_ensemble=data.frame(PA1=c(KAPPA=0,TSS=0,ROC=0))

for (i in 1:5){
  a=w[[i]][,1]
  test_eval_ensemble[paste('PA',i,sep='')]=a
}

test_eval_ensemble['mean']=rowMeans(test_eval_ensemble)

#importancia de variables en modelos por separado

w=as_tibble(all.1659920313.models.out@variables.importances@val,rownames='names')

var_imp_maxent=w %>% select(starts_with('MAXENT.Phillips.Full')) %>% add_column(var=rownames(all.1659920313.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("MAXENT")))) 

var_imp_gbm=w %>% select(starts_with('GBM.Full')) %>% add_column(var=rownames(all.1659920313.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("GBM")))) 

var_imp_rf=w %>% select(starts_with('RF.Full')) %>% add_column(var=rownames(all.1659920313.models.out@variables.importances@val),.before = 1) %>% mutate(mean = rowMeans(across(starts_with("RF")))) 

#importancia de variables en ensambles

w=as_tibble(get_variables_importance(model_en),rownames='names') %>% select(contains(c('all_EMcvByACCURACY_mergedAlgo_Full','names')))
varimp_ensemble=data.frame(PA1=rep(0,length(w$names)));rownames(varimp_ensemble)=w$names

for (i in 1:5){
  o=seq(5*(i-1)+1,i*5)
  a=mutate(w[o], mean = rowMeans(across(starts_with("rand"))))[6]
  varimp_ensemble[paste('PA',i,sep='')]=a
}

varimp_ensemble['mean']=rowMeans(varimp_ensemble)

```

Curvas de respuesta:

Por modelo
```{r}
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
#se carga el modelo a evaluar
load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313.models.out')

all_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313.models.out')
my_model <- get(all_mod)

model=BIOMOD_LoadModels(my_model, models = c('GBM','RF','MAXENT.Phillips'))
model=model[seq(21,315,21)]#se muestrans los modelos "full"

myRespPlot2D <- 
  response.plot2(models = model, Data = get_formal_data(my_model, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean',
    col = c(rep("blue",5), rep("red",5),rep("green",5)),legend = TRUE)
```

Por ensamble
```{r}
#se carga el modelo a evaluar
setwd("S:/UACh/vicuñas/chelsa_historico/bio")
load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313ensemble.models.out')

#se carga el archivo con los ensambles
all_mod=load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313ensemble.models.out')
my_model <- get(all_mod)
#se carga el archivo con los modelos por separado (solo se usa para obtener los valores de las variables)
all_mod2=load('S:/UACh/vicuñas/chelsa_historico/bio/all/all.1659920313.models.out')
my_model2 <- get(all_mod2)

#se seleccionan los ensambles "full" (combinación de corridas), promediados por Accuracy
model=c("all_EMmeanByACCURACY_mergedAlgo_Full_PA1","all_EMmeanByACCURACY_mergedAlgo_Full_PA2","all_EMmeanByACCURACY_mergedAlgo_Full_PA3","all_EMmeanByACCURACY_mergedAlgo_Full_PA4","all_EMmeanByACCURACY_mergedAlgo_Full_PA5")
#para ver todos los ensambles disponibles: 
BIOMOD_LoadModels(my_model, models = c('PA1','PA2','PA3','PA4','PA5'))

#se grafican las curvas de respuesta
myRespPlot2D <- response.plot2(models = model, Data = get_formal_data(my_model2, 'expl.var'),show.variables = c("bio1",  "bio2", "bio3","bio4",  "bio6",  "bio7","bio8","bio10","bio12","bio14","bio15","bio19"),fixed.var.metric = 'mean', col = c('#d9ed92', "#99d98c","#52b69a","#1a759f","#184e77"),legend = TRUE)
```